<img src="https://images.efollett.com/htmlroot/images/templates/storeLogos/CA/864.gif" style="float: right;"> 




# ECON628-01 
### Midterm - Take Home



---
#### Guidelines 
- This is your notebook for your take home midterm. 
- This part of your midterm, as you might expect, is **more challenging** so I highly recommend you to work ASAP. 

- You are required to submit your answers using this notebook (do not push or submit PDFs, Word docs, etc, cause your answers will be considered invalid = **0%**).
- The take home is **15%** of your total midterm score.
- You can work in groups of no more than **3** students.
- Your code **should not be the same** as the rest of your classmates we will check (trust me on this!!), if your code is the same as any of your classmate **your grade will be penalized.**
- The take home is due on **March 20** before class/exam (if you are taking the in-class exam before the rest of the class, you **need** to push your take home part before you commence with the in-class exam) = **NO EXCUSES !!**
- Use this [link][1] to **submit/include** the GitHub link to your take home exam.
[1]: https://docs.google.com/forms/d/e/1FAIpQLSfLkZJY80tw303ss8Ga_2sUMVgumAppWb4tYwssGTbr879_Mw/viewform "link"
- If you find a piece of code online (from someone else), and you decide to use in your midterm, you need:
    - Cite the website from where you are getting the code.
    - **Explain on your "own words" what the code is doing.**
    - If you fail to do this, your grade will be **penalized.**
- Finally, you don't need to 
---

#### The data

The state of Iowa provides many data sets on their website, we will be using a dataset which contains transactions for all stores that have a class E liquor license. 

The data , data dictionary can be found [directly on their website](https://data.iowa.gov/Economy/Iowa-Liquor-Sales/m3tr-qhgy).

**However,** since many of you may have had computer issues reading medium size datasets, **everyone** needs to use the 10% dataset version of Iowa liquor sales, located in your dataset folder. 

---

#### Package imports

In [29]:
import datetime
import statsmodels.api as sm
from sklearn import linear_model

import numpy as np
import scipy.stats as stats
import pandas as pd
import seaborn as sns

import matplotlib
import matplotlib.pyplot as plt

%config InlineBackend.figure_format = 'retina'
%matplotlib inline

plt.style.use('fivethirtyeight')

## 1. Load the data from file

---

In [4]:
booze=pd.read_csv('../../datasets/iowa_liquor/Iowa_Liquor_sales_sample_10pct.csv')

## 2. Do an initial overview of the data

---

At the very least describe the columns/variables and the datatypes.

In [3]:
booze.head()

,Date,Store Number,City,Zip Code,County Number,County,Category,Category Name,Vendor Number,Item Number,Item Description,Bottle Volume (ml),State Bottle Cost,State Bottle Retail,Bottles Sold,Sale (Dollars),Volume Sold (Liters),Volume Sold (Gallons)
0,11/04/2015,3717,SUMNER,50674,9.0,Bremer,1051100.0,APRICOT BRANDIES,55,54436,Mr. Boston Apricot Brandy,750,$4.50,$6.75,12,$81.00,9.0,2.38
1,03/02/2016,2614,DAVENPORT,52807,82.0,Scott,1011100.0,BLENDED WHISKIES,395,27605,Tin Cup,750,$13.75,$20.63,2,$41.26,1.5,0.40
2,02/11/2016,2106,CEDAR FALLS,50613,7.0,Black Hawk,1011200.0,STRAIGHT BOURBON WHISKIES,65,19067,Jim Beam,1000,$12.59,$18.89,24,$453.36,24.0,6.34
3,02/03/2016,2501,AMES,50010,85.0,Story,1071100.0,AMERICAN COCKTAILS,395,59154,1800 Ultimate Margarita,1750,$9.50,$14.25,6,$85.50,10.5,2.77
4,08/18/2015,3654,BELMOND,50421,99.0,Wright,1031080.0,VODKA 80 PROOF,297,35918,Five O'clock Vodka,1750,$7.20,$10.80,12,$129.60,21.0,5.55

In [4]:
booze.describe()

/home/dsi-student/.conda/envs/econ/lib/python2.7/site-packages/numpy/lib/function_base.py:3834: RuntimeWarning: Invalid value encountered in percentile
  RuntimeWarning)

,Store Number,County Number,Category,Vendor Number,Item Number,Bottle Volume (ml),Bottles Sold,Volume Sold (Liters),Volume Sold (Gallons)
count,270955.000000,269878.000000,2.708870e+05,270955.00000,270955.000000,270955.000000,270955.000000,270955.000000,270955.000000
mean,3590.263701,57.231642,1.043888e+06,256.43443,45974.963300,924.830341,9.871285,8.981351,2.372830
std,947.662050,27.341205,5.018211e+04,141.01489,52757.043086,493.088489,24.040912,28.913690,7.638182
min,2106.000000,1.000000,1.011100e+06,10.00000,168.000000,50.000000,1.000000,0.100000,0.030000
25%,2604.000000,NaN,NaN,115.00000,26827.000000,750.000000,2.000000,1.500000,0.400000
50%,3722.000000,NaN,NaN,260.00000,38176.000000,750.000000,6.000000,5.250000,1.390000
75%,4378.000000,NaN,NaN,380.00000,64573.000000,1000.000000,12.000000,10.500000,2.770000
max,9023.000000,99.000000,1.701100e+06,978.00000,995507.000000,6000.000000,2508.000000,2508.000000,662.540000

In [5]:
booze.shape

(270955, 18)

In [6]:
booze.describe().T

,count,mean,std,min,25%,50%,75%,max
Store Number,270955.0,3.590264e+03,947.662050,2106.00,2604.0,3722.00,4378.00,9023.00
County Number,269878.0,5.723164e+01,27.341205,1.00,NaN,NaN,NaN,99.00
Category,270887.0,1.043888e+06,50182.111075,1011100.00,NaN,NaN,NaN,1701100.00
Vendor Number,270955.0,2.564344e+02,141.014890,10.00,115.0,260.00,380.00,978.00
Item Number,270955.0,4.597496e+04,52757.043086,168.00,26827.0,38176.00,64573.00,995507.00
Bottle Volume (ml),270955.0,9.248303e+02,493.088489,50.00,750.0,750.00,1000.00,6000.00
Bottles Sold,270955.0,9.871285e+00,24.040912,1.00,2.0,6.00,12.00,2508.00
Volume Sold (Liters),270955.0,8.981351e+00,28.913690,0.10,1.5,5.25,10.50,2508.00
Volume Sold (Gallons),270955.0,2.372830e+00,7.638182,0.03,0.4,1.39,2.77,662.54

In [7]:
booze.info
# okay can see that some of the columns use dollar signs, which is probably a problem. Need to look into that
#Okay first column is just N, then date, store, then store number, City, Zip, county number?

<bound method DataFrame.info of               Date  Store Number             City Zip Code  County Number  \
0       11/04/2015          3717           SUMNER    50674            9.0
1       03/02/2016          2614        DAVENPORT    52807           82.0
2       02/11/2016          2106      CEDAR FALLS    50613            7.0
3       02/03/2016          2501             AMES    50010           85.0
4       08/18/2015          3654          BELMOND    50421           99.0
5       04/20/2015          2569     CEDAR RAPIDS    52402           57.0
6       08/05/2015          2596          OTTUMWA    52501           90.0
7       06/25/2015          3456       CLEAR LAKE    50428           17.0
8       01/04/2016          4757        BONDURANT    50035           77.0
9       11/10/2015          4346       SHELLSBURG    52332            6.0
10      09/28/2015          2648  WEST DES MOINES    50265           77.0
11      10/28/2015          2600        OSKALOOSA    52577           62.0
12      01/22/2015          3858        DAVENPORT    52806           82.0
13      02/29/2016          4673       WEST POINT    52656           56.0
14      01/04/2016          2670       CORALVILLE    52241           52.0
15      06/10/2015          3717           SUMNER    50674            9.0
16      02/25/2016          2130         WATERLOO    50703            7.0
17      12/29/2015          2600        OSKALOOSA    52577           62.0
18      12/26/2015          4604           NEWTON    50208           50.0
19      03/04/2015          2614        DAVENPORT    52807           82.0
20      01/16/2015          2590     CEDAR RAPIDS    52402           57.0
21      01/13/2015          3942           TOLEDO    52342           86.0
22      03/24/2015          3981     SIOUX CENTER    51250           84.0
23      11/12/2015          4376       MASON CITY    50401           17.0
24      03/14/2016          2618     CEDAR RAPIDS    52402           57.0
25      02/03/2015          3390          MILFORD    51351           30.0
26      11/23/2015          3565        IOWA CITY    52246           52.0
27      04/21/2015          3963   COUNCIL BLUFFS    51501           78.0
28      12/01/2015          4375           GRIMES    50111           77.0
29      01/14/2015          2545        IOWA CITY    52245           52.0
...            ...           ...              ...      ...            ...
270925  01/05/2015          2837         WATERLOO    50702            7.0
270926  12/26/2015          2478          ALTOONA    50009           77.0
270927  08/31/2015          2633       DES MOINES    50320           77.0
270928  10/07/2015          3896        IOWA CITY    52240           52.0
270929  01/25/2016          5070           WILTON    52778           70.0
270930  10/13/2015          4634     CEDAR RAPIDS    52402           57.0
270931  05/26/2015          2602     WEBSTER CITY    50595           40.0
270932  06/18/2015          4604           NEWTON    50208           50.0
270933  02/26/2015          4987             AMES    50010           85.0
270934  03/18/2015          2623       SIOUX CITY    51104           97.0
270935  06/08/2015          5126       DES MOINES    50310           77.0
270936  03/31/2015          2552     CEDAR RAPIDS    52404           57.0
270937  01/27/2015          2553          CRESTON    50801           88.0
270938  04/29/2015          3890     CEDAR RAPIDS    52405           57.0
270939  05/04/2015          4876         HIAWATHA    52233           57.0
270940  01/21/2015          2523      CENTERVILLE    52544            4.0
270941  02/09/2015          4856           LISBON    52253           57.0
270942  06/15/2015          2512        IOWA CITY    52240           52.0
270943  10/21/2015          4438             AMES    50010           85.0
270944  03/22/2016          2620  WINDSOR HEIGHTS    50311           77.0
270945  06/11/2015          2627       DES MOINES    50310           77.0
270946  11/24/2015          5162        URBANDALE    50322           77.0
270947  05/12/2015          4375           GRIMES    50111           77.0
270948  04/08/2015          2545        IOWA CITY    52245           52.0
270949  07/21/2015          2529     CEDAR RAPIDS    52405           57.0
270950  12/22/2015          4057       DES MOINES    50316           77.0
270951  11/04/2015          5151        IDA GROVE    51445           47.0
270952  10/20/2015          5152         WATERLOO    50702            7.0
270953  11/20/2015          3562  WEST BURLINGTON    52655           29.0
270954  01/27/2015          4446        URBANDALE    50322           77.0

               County   Category                       Category Name  \
0              Bremer  1051100.0                    APRICOT BRANDIES
1               Scott  1011100.0                    BLENDED WHISKIES
2          Black Hawk  1011200.0           STRAIGHT BOURBON WHISKIES
3               Story  1071100.0                  AMERICAN COCKTAILS
4              Wright  1031080.0                      VODKA 80 PROOF
5                Linn  1041100.0                   AMERICAN DRY GINS
6             Wapello  1051010.0             AMERICAN GRAPE BRANDIES
7         Cerro Gordo  1012100.0                   CANADIAN WHISKIES
8                Polk  1032080.0                      IMPORTED VODKA
9              Benton  1081315.0                   CINNAMON SCHNAPPS
10               Polk  1011250.0      SINGLE BARREL BOURBON WHISKIES
11            Mahaska  1071100.0                  AMERICAN COCKTAILS
12              Scott  1012100.0                   CANADIAN WHISKIES
13                Lee  1081300.0                 PEPPERMINT SCHNAPPS
14            Johnson  1031200.0                      VODKA FLAVORED
15             Bremer  1051100.0                    APRICOT BRANDIES
16         Black Hawk  1031100.0                     100 PROOF VODKA
17            Mahaska  1031200.0                      VODKA FLAVORED
18             Jasper  1081700.0         DISTILLED SPIRITS SPECIALTY
19              Scott  1012100.0                   CANADIAN WHISKIES
20               Linn  1031200.0                      VODKA FLAVORED
21               Tama  1012100.0                   CANADIAN WHISKIES
22              Sioux  1011100.0                    BLENDED WHISKIES
23        Cerro Gordo  1022100.0                             TEQUILA
24               Linn  1031080.0                      VODKA 80 PROOF
25          Dickinson  1011300.0                  TENNESSEE WHISKIES
26            Johnson  1012100.0                   CANADIAN WHISKIES
27      Pottawattamie  1011100.0                    BLENDED WHISKIES
28               Polk  1031080.0                      VODKA 80 PROOF
29            Johnson  1081600.0                     WHISKEY LIQUEUR
...               ...        ...                                 ...
270925     Black Hawk  1081200.0                      CREAM LIQUEURS
270926           Polk  1022100.0                             TEQUILA
270927           Polk  1031200.0                      VODKA FLAVORED
270928        Johnson  1031080.0                      VODKA 80 PROOF
270929      Muscatine  1031080.0                      VODKA 80 PROOF
270930           Linn  1031080.0                      VODKA 80 PROOF
270931       Hamilton  1081900.0  MISC. AMERICAN CORDIALS & LIQUEURS
270932         Jasper  1011300.0                  TENNESSEE WHISKIES
270933          Story  1062310.0                          SPICED RUM
270934       Woodbury  1051110.0                 BLACKBERRY BRANDIES
270935           Polk  1011300.0                  TENNESSEE WHISKIES
270936           Linn  1022100.0                             TEQUILA
270937          Union  1082900.0  MISC. IMPORTED CORDIALS & LIQUEURS
270938           Linn  1031080.0                      VODKA 80 PROOF
270939           Linn  1031200.0                      VODKA FLAVORED
270940      Appanoose  1012200.0                     SCOTCH WHISKIES
270941           Linn  1031080.0                      VODKA 80 PROOF
270942        Johnson  1011100.0                    BLENDED WHISKIES
270943          Story  1011200.0           STRAIGHT BOURBON WHISKIES
270944           Polk  1081240.0               GREEN CREME DE MENTHE
270945           Polk  1062200.0    PUERTO RICO & VIRGIN ISLANDS RUM
270946           Polk  1031080.0                      VODKA 80 PROOF
270947           Polk  1062310.0                          SPICED RUM
270948        Johnson  1062300.0                        FLAVORED RUM
270949           Linn  1031100.0                     100 PROOF VODKA
270950           Polk  1022100.0                             TEQUILA
270951            Ida  1011200.0           STRAIGHT BOURBON WHISKIES
270952     Black Hawk  1011300.0                  TENNESSEE WHISKIES
270953     Des Moines  1082900.0  MISC. IMPORTED CORDIALS & LIQUEURS
270954           Polk  1031080.0                      VODKA 80 PROOF

        Vendor Number  Item Number                       Item Description  \
0                  55        54436              Mr. Boston Apricot Brandy
1                 395        27605                                Tin Cup
2                  65        19067                               Jim Beam
3                 395        59154                1800 Ultimate Margarita
4                 297        35918                     Five O'clock Vodka
5                 205        31473                      New Amsterdam Gin
6                  85        52806                          Korbel Brandy
7                  65        10628                   Canadian Club Whisky
8                 370        34006           Absolut Swedish Vodka 80 Prf
9                  65        82610                     Dekuyper Hot Damn!
10                 65        19235       Knob Creek Single Barrel Reserve
11                 55        57148          Chi-Chi's Margarita W/tequila
12                 65        15248                   Windsor Canadian Pet
13                322        75211                          Kinky Liqueur
14                380        41705                  Uv Red (cherry) Vodka
15                 55        54436              Mr. Boston Apricot Brandy
16                297        35913                     Five O'clock Vodka
17                380        41989                          Uv Cake Vodka
18                434        75087                        Juarez Gold Dss
19                434        13638           Lord Calvert Canadian Whisky
20                971        41474                   44 North Huckleberry
21                115        11786                  Black Velvet Traveler
22                260        25606            Seagrams 7 Crown Bl Whiskey
23                395        89196  Jose Cuervo Especial Reposado Tequila
24                297        35926                 Five O'clock PET Vodka
25                 85        26827          Jack Daniels Old #7 Black Lbl
26                260        11290       Crown Royal Canadian Whisky Mini
27                434        24156                  Hawkeye Blend Whiskey
28                380        37338                           UV Vodka PET
29                260        66199                 Piehole Apple Pie Mini
...               ...          ...                                    ...
270925            260        68306             Emmets Irish Cream Liqueur
270926            410        89646                           Patron Anejo
270927            260        77699                        Smirnoff Orange
270928            300        36904                    Mccormick Vodka Pet
270929            380        37346                         Phillips Vodka
270930            297        35914                     Five O'clock Vodka
270931             65        85526        Dekuyper Signature Blue Curacao
270932             85        26828          Jack Daniels Old #7 Black Lbl
270933            260        43336         Captain Morgan Original Spiced
270934             55        55068           Mr. Boston Blackberry Brandy
270935             85        86670          Jack Daniel's Tennessee Honey
270936            395        89196  Jose Cuervo Especial Reposado Tequila
270937             85        64676      Chambord Liqueur Royale De France
270938            260        37994                  Smirnoff Vodka 80 Prf
270939            380        42002                          Uv Cake Vodka
270940            305         4936                   Famous Grouse Scotch
270941             55        35948       Fleischmann's Royal Vodka 80 Prf
270942             65        24466         Kessler Blend Whiskey Traveler
270943             65        19061                          Jim Beam Mini
270944            434        79336        Paramount Creme De Menthe/green
270945             55        44215                       Barton Light Rum
270946            301        38176                            Titos Vodka
270947            260        43334              Captain Morgan Spiced Rum
270948             35        43145               Bacardi Pineapple Fusion
270949            300        36887                        McCormick Vodka
270950            410        88291             Patron Tequila Silver Mini
270951            259        17956              Evan Williams Str Bourbon
270952             85        26826          Jack Daniels Old #7 Black Lbl
270953            192        65258                   Jagermeister Liqueur
270954            260        37993                  Smirnoff Vodka 80 Prf

        Bottle Volume (ml) State Bottle Cost State Bottle Retail  \
0                      750             $4.50               $6.75
1                      750            $13.75              $20.63
2                     1000            $12.59              $18.89
3                     1750             $9.50              $14.25
4                     1750             $7.20              $10.80
5                     1750            $13.32              $19.98
6                      750             $6.66               $9.99
7                     1750            $15.75              $23.63
8                      750            $11.49              $17.24
9                     1000             $7.62              $11.43
10                     750            $26.24              $39.36
11                    1750             $6.00               $9.25
12                    1750             $8.92              $13.38
13                     750            $10.00              $15.00
14                    1000             $7.50              $11.25
15                     750             $4.50               $6.75
16                     200             $1.13               $1.70
17                     750             $6.50               $9.75
18                    1000             $4.92               $7.38
19                    1750             $9.97              $14.96
20                     750            $14.25              $21.38
21                     750             $5.23               $7.85
22                     750             $7.00              $10.50
23                     750            $10.49              $15.74
24                     750             $3.37               $5.06
25                    1000            $17.90              $26.85
26                     300             $7.35              $11.03
27                     750             $3.50               $5.25
28                    1750            $10.99              $16.49
29                     500             $4.90               $7.35
...                    ...               ...                 ...
270925                 750             $6.00               $9.00
270926                 750            $31.00              $46.50
270927                1000             $9.25              $13.88
270928                 375             $1.80               $2.70
270929                 750             $3.57               $5.36
270930                 375             $1.93               $2.90
270931                 750             $5.25               $7.88
270932                1750            $29.67              $44.51
270933                 750             $9.00              $13.50
270934                1750            $10.00              $15.00
270935                 750            $15.07              $22.61
270936                 750            $10.49              $15.74
270937                 750            $18.56              $27.84
270938                 375             $4.75               $7.13
270939                 500             $4.89               $7.34
270940                 750            $12.03              $18.05
270941                1750             $6.68              $10.27
270942                 750             $5.51               $8.27
270943                 500             $6.83              $10.25
270944                 750             $4.75               $7.13
270945                 100             $0.89               $1.34
270946                 750             $9.65              $14.48
270947                 375             $5.00               $7.50
270948                 750             $8.50              $12.75
270949                1000             $4.13               $6.20
270950                 300            $20.30              $30.45
270951                 750             $7.47              $11.21
270952                 750            $15.07              $22.61
270953                1750            $26.05              $39.08
270954                 200             $2.75               $4.13

        Bottles Sold Sale (Dollars)  Volume Sold (Liters)  \
0                 12         $81.00                  9.00
1                  2         $41.26                  1.50
2                 24        $453.36                 24.00
3                  6         $85.50                 10.50
4                 12        $129.60                 21.00
5                  6        $119.88                 10.50
6                  3         $29.97                  2.25
7                  2         $47.26                  3.50
8                  4         $68.96                  3.00
9                  2         $22.86                  2.00
10                 6        $236.16                  4.50
11                 6         $55.50                 10.50
12                 1         $13.38                  1.75
13                12        $180.00                  9.00
14                12        $135.00                 12.00
15                 4         $27.00                  3.00
16                48         $81.60                  9.60
17                12        $117.00                  9.00
18                24        $177.12                 24.00
19                 6         $89.76                 10.50
20                 2         $42.76                  1.50
21                12         $94.20                  9.00
22                12        $126.00                  9.00
23                12        $188.88                  9.00
24                12         $60.72                  9.00
25                24        $644.40                 24.00
26                 1         $11.03                  0.30
27                 3         $15.75                  2.25
28                 6         $98.94                 10.50
29                 1          $7.35                  0.50
...              ...            ...                   ...
270925             4         $36.00                  3.00
270926             6        $279.00                  4.50
270927            12        $166.56                 12.00
270928            48        $129.60                 18.00
270929             4         $21.44                  3.00
270930            12         $34.80                  4.50
270931            12         $94.56                  9.00
270932             2         $89.02                  3.50
270933             3         $40.50                  2.25
270934             2         $30.00                  3.50

In [13]:
# Cheap, high quanity alcohol sold the most. Side note; Hawkeye is quite possibly the worst vodka on this planet.
booze.groupby(['Item Description'], sort=True)[['Bottles Sold']].sum().sort_values(by=['Bottles Sold'], ascending=False).reset_index()

                                     Item Description  Bottles Sold
0                                        Black Velvet        148345
1                                       Hawkeye Vodka        100530
2                           Captain Morgan Spiced Rum         65756
3                                  Five O'clock Vodka         64476
4                           Fireball Cinnamon Whiskey         58595
5                                        Barton Vodka         48565
6                                 Mccormick Vodka Pet         48046
7                       Jack Daniels Old #7 Black Lbl         45825
8                               Smirnoff Vodka 80 Prf         38581
9                                     Mccormick Vodka         35586
10                       Absolut Swedish Vodka 80 Prf         33556
11                    Paul Masson Grande Amber Brandy         32174
12                               Bacardi Superior Rum         30339
13                        Crown Royal Canadian Whisky         29366
14                                     Phillips Vodka         29085
15                                          Five Star         28636
16                        Seagrams 7 Crown Bl Whiskey         28606
17                                           Jim Beam         27013
18                          Admiral Nelson Spiced Rum         26730
19                               Jagermeister Liqueur         26405
20              Jose Cuervo Especial Reposado Tequila         26351
21                             Seagrams Extra Dry Gin         25120
22                                   Grey Goose Vodka         24512
23                                 Malibu Coconut Rum         23872
24                                        Hennessy VS         23002
25                     Captain Morgan Original Spiced         22395
26                           Fireball Cinnamon Whisky         22104
27                                   Southern Comfort         22023
28                                Paramount White Rum         21883
29                                Canadian Ltd Whisky         20164
...                                               ...           ...
2143                         Calumet Farm Bourbon VAP             1
2144                                  Bowmore 18YR HA             1
2145                          Tooters Rainbow 12 Pack             1
2146                              Caribou Crossing HA             1
2147      Parkers Heritage Collection Malt Whiskey HA             1
2148      Salvador's Strawberry Margarita 200ml-4Pack             1
2149                                 Caol Ila 30YR HA             1
2150                           Yahara Bay Orangecello             1
2151                                          Bulleit             1
2152                Old Rip Van Winkle 20yr(pappy) HA             1
2153                                Hangar One Citron             1
2154            Wicked 87 American Light Whiskey Mini             1
2155                    Jim Beam Signature Craft 12YR             1
2156               Johnnie Walker Blue Gift Bottle HA             1
2157                             Spiked Apple Spirits             1
2158                  Hennessy 250 Collector Blend HA             1
2159  Johnnie Walker Private Collection 2015 Fruit HA             1
2160                                     Kru Cucumber             1
2161                               Kru Pistachio Mini             1
2162                                   Svedka 100 Prf             1
2163                         El Mayor 50ml Trial Pack             1
2164            Skyy Infusions Pacific Blueberry Mini             1
2165                                Five Star Pegasus             1
2166                      Skyy Coastal Cranberry Mini             1
2167                             Elijah Craig 23YR HA             1
2168                              Midnight Moon Peach             1
2169                                     Minnesota 14             1
2170                                 Mortlach 18YR HA             1
2171          Irish Single Malt 14yr- Brother in Arms             1
2172               Elijah Craig 18yr Single Barrel HA             1

[2173 rows x 2 columns]


## 3. Clean the dataset

---

### 3.1 Identify columns that you will need to convert and clean. Where and how is the data corrupted?

Don't worry about converting the date column to a pandas/numpy "datetime" datatype, unless you want to (not required for these problems and is a challenging thing to work with in its own right.)

In [9]:
booze.isnull().sum()
#Okay clearly we have some missing values in 4 of our 18 columns.

Date                        0
Store Number                0
City                        0
Zip Code                    0
County Number            1077
County                   1077
Category                   68
Category Name             632
Vendor Number               0
Item Number                 0
Item Description            0
Bottle Volume (ml)          0
State Bottle Cost           0
State Bottle Retail         0
Bottles Sold                0
Sale (Dollars)              0
Volume Sold (Liters)        0
Volume Sold (Gallons)       0
dtype: int64

In [13]:
booze.isnull().any()

Date                     False
Store Number             False
City                     False
Zip Code                 False
County Number             True
County                    True
Category                  True
Category Name             True
Vendor Number            False
Item Number              False
Item Description         False
Bottle Volume (ml)       False
State Bottle Cost        False
State Bottle Retail      False
Bottles Sold             False
Sale (Dollars)           False
Volume Sold (Liters)     False
Volume Sold (Gallons)    False
dtype: bool

In [14]:
booze["Category Name"]

0                           APRICOT BRANDIES
1                           BLENDED WHISKIES
2                  STRAIGHT BOURBON WHISKIES
3                         AMERICAN COCKTAILS
4                             VODKA 80 PROOF
5                          AMERICAN DRY GINS
6                    AMERICAN GRAPE BRANDIES
7                          CANADIAN WHISKIES
8                             IMPORTED VODKA
9                          CINNAMON SCHNAPPS
10            SINGLE BARREL BOURBON WHISKIES
11                        AMERICAN COCKTAILS
12                         CANADIAN WHISKIES
13                       PEPPERMINT SCHNAPPS
14                            VODKA FLAVORED
15                          APRICOT BRANDIES
16                           100 PROOF VODKA
17                            VODKA FLAVORED
18               DISTILLED SPIRITS SPECIALTY
19                         CANADIAN WHISKIES
20                            VODKA FLAVORED
21                         CANADIAN WHISKIES
22                          BLENDED WHISKIES
23                                   TEQUILA
24                            VODKA 80 PROOF
25                        TENNESSEE WHISKIES
26                         CANADIAN WHISKIES
27                          BLENDED WHISKIES
28                            VODKA 80 PROOF
29                           WHISKEY LIQUEUR
                         ...
270925                        CREAM LIQUEURS
270926                               TEQUILA
270927                        VODKA FLAVORED
270928                        VODKA 80 PROOF
270929                        VODKA 80 PROOF
270930                        VODKA 80 PROOF
270931    MISC. AMERICAN CORDIALS & LIQUEURS
270932                    TENNESSEE WHISKIES
270933                            SPICED RUM
270934                   BLACKBERRY BRANDIES
270935                    TENNESSEE WHISKIES
270936                               TEQUILA
270937    MISC. IMPORTED CORDIALS & LIQUEURS
270938                        VODKA 80 PROOF
270939                        VODKA FLAVORED
270940                       SCOTCH WHISKIES
270941                        VODKA 80 PROOF
270942                      BLENDED WHISKIES
270943             STRAIGHT BOURBON WHISKIES
270944                 GREEN CREME DE MENTHE
270945      PUERTO RICO & VIRGIN ISLANDS RUM
270946                        VODKA 80 PROOF
270947                            SPICED RUM
270948                          FLAVORED RUM
270949                       100 PROOF VODKA
270950                               TEQUILA
270951             STRAIGHT BOURBON WHISKIES
270952                    TENNESSEE WHISKIES
270953    MISC. IMPORTED CORDIALS & LIQUEURS
270954                        VODKA 80 PROOF
Name: Category Name, dtype: object

In [15]:
booze.dtypes
# We have a few columns as objects that need to be converted.

Date                      object
Store Number               int64
City                      object
Zip Code                  object
County Number            float64
County                    object
Category                 float64
Category Name             object
Vendor Number              int64
Item Number                int64
Item Description          object
Bottle Volume (ml)         int64
State Bottle Cost         object
State Bottle Retail       object
Bottles Sold               int64
Sale (Dollars)            object
Volume Sold (Liters)     float64
Volume Sold (Gallons)    float64
dtype: object

In [8]:
#After extensive thinking, ive decided to drop NA values.
booze = booze.dropna()

In [41]:
booze.isnull().sum()

Date                     0
Store Number             0
City                     0
Zip Code                 0
County Number            0
County                   0
Category                 0
Category Name            0
Vendor Number            0
Item Number              0
Item Description         0
Bottle Volume (ml)       0
State Bottle Cost        0
State Bottle Retail      0
Bottles Sold             0
Sales                    0
Volume Sold (Liters)     0
Volume Sold (Gallons)    0
dtype: int64

In [9]:
# converting county number and category to integers
booze["County Number"] = booze["County Number"].astype(int)
booze["Category"] = booze["Category"].astype(int)

In [10]:
#But first lets change the name of one of our columns
booze.rename(columns={
        'Sale (Dollars)':'Sales',
    }, inplace=True)

In [11]:
booze[['Sales']].tail()

          Sales
270950  $121.80
270951   $33.63
270952  $135.66
270953  $234.48
270954   $33.04

In [12]:
booze["Sales"] = booze["Sales"].apply(lambda x: x.replace('$','')).astype(float)
# successfully took out the dollar sign and converted the sales column to a float

In [13]:
booze['Sales'].head()

0     81.00
1     41.26
2    453.36
3     85.50
4    129.60
Name: Sales, dtype: float64

In [14]:
booze["State Bottle Cost"] = booze["State Bottle Cost"].apply(lambda x: x.replace('$','')).astype(float)

In [138]:
booze.head(20)

,Date,Store Number,City,Zip Code,County Number,County,Category,Category Name,Vendor Number,Item Number,...,Bottle Volume (ml),State Bottle Cost,State Bottle Retail,Bottles Sold,Sales,Volume Sold (Liters),Volume Sold (Gallons),Profit,Price per Gallon,Profit per Gallon
22111,2015-01-08,2106,CEDAR FALLS,50613,7,Black Hawk,1062200,PUERTO RICO & VIRGIN ISLANDS RUM,35,43127,...,1000,9.50,14.25,36,513.00,36.0,9.51,171.00,53.943218,17.981073
47659,2015-01-08,2106,CEDAR FALLS,50613,7,Black Hawk,1022100,TEQUILA,410,88296,...,750,27.00,40.50,12,486.00,9.0,2.38,162.00,204.201681,68.067227
65214,2015-01-08,2106,CEDAR FALLS,50613,7,Black Hawk,1062310,SPICED RUM,259,43026,...,750,5.78,8.67,12,104.04,9.0,2.38,34.68,43.714286,14.571429
66346,2015-01-08,2106,CEDAR FALLS,50613,7,Black Hawk,1081200,CREAM LIQUEURS,305,73055,...,750,12.50,18.75,12,225.00,9.0,2.38,75.00,94.537815,31.512605
80570,2015-01-08,2106,CEDAR FALLS,50613,7,Black Hawk,1062200,PUERTO RICO & VIRGIN ISLANDS RUM,434,46351,...,1000,4.34,6.51,12,78.12,12.0,3.17,26.04,24.643533,8.214511
105659,2015-01-08,2106,CEDAR FALLS,50613,7,Black Hawk,1032080,IMPORTED VODKA,434,34546,...,750,7.86,11.79,12,141.48,9.0,2.38,47.16,59.445378,19.815126
110707,2015-01-08,2106,CEDAR FALLS,50613,7,Black Hawk,1081900,MISC. AMERICAN CORDIALS & LIQUEURS,322,75214,...,750,10.00,15.00,12,180.00,9.0,2.38,60.00,75.630252,25.210084
130957,2015-01-08,2106,CEDAR FALLS,50613,7,Black Hawk,1081317,GRAPE SCHNAPPS,65,82637,...,1000,7.62,11.43,12,137.16,12.0,3.17,45.72,43.268139,14.422713
144321,2015-01-08,2106,CEDAR FALLS,50613,7,Black Hawk,1012100,CANADIAN WHISKIES,260,11297,...,1000,18.50,27.75,36,999.00,36.0,9.51,333.00,105.047319,35.015773
165212,2015-01-08,2106,CEDAR FALLS,50613,7,Black Hawk,1031080,VODKA 80 PROOF,434,36307,...,1000,4.05,6.08,12,72.96,12.0,3.17,24.36,23.015773,7.684543
175048,2015-01-08,2106,CEDAR FALLS,50613,7,Black Hawk,1082900,MISC. IMPORTED CORDIALS & LIQUEURS,192,65257,...,1000,15.54,23.31,72,1678.32,72.0,19.02,559.44,88.239748,29.413249
193161,2015-01-08,2106,CEDAR FALLS,50613,7,Black Hawk,1012100,CANADIAN WHISKIES,260,11296,...,750,15.00,22.50,12,270.00,9.0,2.38,90.00,113.445378,37.815126
223428,2015-01-08,2106,CEDAR FALLS,50613,7,Black Hawk,1041100,AMERICAN DRY GINS,55,29287,...,1000,3.92,5.88,12,70.56,12.0,3.17,23.52,22.258675,7.419558
238277,2015-01-08,2106,CEDAR FALLS,50613,7,Black Hawk,1031200,VODKA FLAVORED,380,41694,...,1000,7.50,11.25,12,135.00,12.0,3.17,45.00,42.586751,14.195584
13533,2015-01-15,2106,CEDAR FALLS,50613,7,Black Hawk,1012300,IRISH WHISKIES,240,15940,...,750,14.38,21.57,12,258.84,9.0,2.38,86.28,108.756303,36.252101
22526,2015-01-15,2106,CEDAR FALLS,50613,7,Black Hawk,1081400,TRIPLE SEC,421,86637,...,1000,3.01,4.52,12,54.24,12.0,3.17,18.12,17.110410,5.716088
130870,2015-01-15,2106,CEDAR FALLS,50613,7,Black Hawk,1081315,CINNAMON SCHNAPPS,380,84636,...,750,7.45,11.18,12,134.16,9.0,2.38,44.76,56.369748,18.806723
158419,2015-01-15,2106,CEDAR FALLS,50613,7,Black Hawk,1022100,TEQUILA,395,89197,...,1000,12.50,18.75,48,900.00,48.0,12.68,300.00,70.977918,23.659306
187130,2015-01-15,2106,CEDAR FALLS,50613,7,Black Hawk,1031080,VODKA 80 PROOF,55,35318,...,1750,6.92,10.38,6,62.28,10.5,2.77,20.76,22.483755,7.494585
199964,2015-01-15,2106,CEDAR FALLS,50613,7,Black Hawk,1031080,VODKA 80 PROOF,55,35317,...,1000,3.97,5.96,120,715.20,120.0,31.70,238.80,22.561514,7.533123

In [15]:
booze["State Bottle Retail"] = booze["State Bottle Retail"].apply(lambda x: x.replace('$','')).astype(float)

### 3.2 Clean the columns

In [ ]:
# Kind of did this above, will move it down later


### 3.3 Perform more extensive cleaning of the dataset

Cleaning of data can mean a lot more than just fixing strings and numbers in columns. There are often logical errors with data, useless or nonsensical categories, redundancy of information, outliers, and many more problems.

This dataset has problems beyond just fixing the types of columns. Keep in mind that some types of "data cleaning" is subjective: it's not always a cut-and-dry conversion of type or removal of null values. Subjectivity when dealing with data is just a fact of life when dealing with data. This isn't a kind of programming where things are just right or wrong.

In [30]:
# covert the date column to date-time format, not sure if this will work.
booze["Date"] = pd.to_datetime(booze["Date"], format="%m/%d/%Y")

In [31]:
booze["Date"].head()

0   2015-11-04
1   2016-03-02
2   2016-02-11
3   2016-02-03
4   2015-08-18
Name: Date, dtype: datetime64[ns]

In [17]:
booze['Category'].isnull().sum()

0

In [18]:
booze['Item Description'].isnull().any()

False

In [27]:
# Okay so category name has quite a few missing values but item description does not. Item description usually says what type of alcohol it is. 
alc_type=['Whiskey'] for "Category"==1011100.0

SyntaxError: invalid syntax (<ipython-input-27-330ffd6b3b29>, line 2)

In [34]:
alc_type={whiskey: "whiskey", 2: "vodka", 3: "rum", 4: "beer"}

In [35]:
print alc_type

{1: 'whiskey', 2: 'vodka', 3: 'rum', 4: 'beer'}

In [36]:
alc_type[2]

'vodka'

In [43]:
alc_type = {'whiskey'} if 'whiskey' in "Item Description"

SyntaxError: invalid syntax (<ipython-input-43-0831cbf0d1ad>, line 1)

In [12]:
# Looking at item description by liters sold
booze.groupby(['Item Description'], sort=True)[['Volume Sold (Liters)']].sum().sort_values(by=['Volume Sold (Liters)'], ascending=False).reset_index()

                                 Item Description  Volume Sold (Liters)
0                                    Black Velvet             170805.70
1                                   Hawkeye Vodka             110968.35
2                       Captain Morgan Spiced Rum              68305.01
3                              Five O'clock Vodka              57913.35
4                                    Barton Vodka              57088.78
5                       Fireball Cinnamon Whiskey              56501.30
6                   Jack Daniels Old #7 Black Lbl              43168.70
7                                  Phillips Vodka              36953.75
8                    Absolut Swedish Vodka 80 Prf              31765.45
9                            Bacardi Superior Rum              31439.15
10                    Seagrams 7 Crown Bl Whiskey              30127.53
11                            Mccormick Vodka Pet              29560.33
12                      Admiral Nelson Spiced Rum              29534.72
13                    Crown Royal Canadian Whisky              28846.86
14                          Smirnoff Vodka 80 Prf              28836.11
15                            Paramount White Rum              26230.20
16                                       Jim Beam              24152.29
17                   Captain Morgan Spiced Barrel              23868.25
18                            Canadian Ltd Whisky              22967.14
19                                      Five Star              22240.81
20                             Malibu Coconut Rum              22221.08
21          Jose Cuervo Especial Reposado Tequila              21206.70
22                           Jagermeister Liqueur              20795.61
23                           Titos Handmade Vodka              20509.59
24                                  Nikolai Vodka              20179.42
25           Jose Cuervo Authentic Lime Margarita              20038.75
26                            Juarez Tequila Gold              19115.75
27                                     Skol Vodka              18256.78
28                      Uv Blue (raspberry) Vodka              17847.10
29                               Grey Goose Vodka              17647.63
...                                           ...                   ...
2143             Penthouse Spirits Cherry for Him                  0.75
2144               Rebel Yell Small Batch Reserve                  0.75
2145                Jim Beam Signature Craft 12YR                  0.75
2146           Johnnie Walker Blue Gift Bottle HA                  0.75
2147                               Svedka 100 Prf                  0.75
2148                    Rogue Hazelnut Spiced Rum                  0.75
2149  Parkers Heritage Collection Malt Whiskey HA                  0.75
2150                              Bowmore 18YR HA                  0.75
2151                          Caribou Crossing HA                  0.75
2152                         Elijah Craig 23YR HA                  0.75
2153                             Mortlach 18YR HA                  0.75
2154                                 Minnesota 14                  0.75
2155                                    Arrow Gin                  0.75
2156            Old Rip Van Winkle 20yr(pappy) HA                  0.75
2157           Elijah Craig 18yr Single Barrel HA                  0.75
2158                          Midnight Moon Peach                  0.75
2159                         Spiked Apple Spirits                  0.75
2160                             Caol Ila 30YR HA                  0.75
2161                           La Collection Flag                  0.60
2162                           Kru Pistachio Mini                  0.60
2163        Wicked 87 American Light Whiskey Mini                  0.60
2164                                 Auchentoshan                  0.60
2165      Paul Masson Red Berry Grande Amber Mini                  0.60
2166                            Maker's Mark Mini                  0.50
2167        Skyy Infusions Pacific Blueberry Mini                  0.50
2168                  Skyy Coastal Cranberry Mini                  0.50
2169                            Five Star Pegasus                  0.38
2170                             Mac Spey Blended                  0.30
2171                                  Fettercairn                  0.30
2172                     El Mayor 50ml Trial Pack                  0.15

[2173 rows x 2 columns]


## 4. Filter/adjust the store data

---

Some stores may have opened or closed in 2015. These stores will have incorrect yearly summary statistics since they were not open the full year. We need to filter them out or find another way to deal with the inconsistent numbers of months across stores.

It is up to you how you want to deal with this problem.

1. Investigate problematic stores.
2. Decide on an approach to deal with stores not open for the full 2015 year.
3. Implement your plan.
4. Briefly report on what you did and why.

In [20]:
agg_columns = ['Sales', 'Volume Sold (Liters)']
print agg_columns
# aggregating just these two columns of interest in order to use groupby more efficiently

['Sales', 'Volume Sold (Liters)']

In [21]:
store_summary = booze.groupby('Store Number')[agg_columns].sum().reset_index()
print store_summary
# Have matched up store number with sales and liters sold.

      Store Number      Sales  Volume Sold (Liters)
0             2106  176517.45              11836.10
1             2113   11376.12                836.85
2             2130  139440.02               8436.27
3             2152    8625.74                720.87
4             2178   29912.68               2437.92
5             2190  153492.12               7769.28
6             2191  172431.69              10981.44
7             2200   26986.42               2136.02
8             2205   24623.01               1555.41
9             2228   20548.45               1576.50
10            2233   36075.99               2958.31
11            2238   12171.88                717.75
12            2248   81680.50               3364.51
13            2285   89165.92               4523.85
14            2290   68737.73               4478.63
15            2327   12441.71                981.38
16            2353   55899.13               4723.65
17            2367    5010.83                346.75
18            2413  112990.69               7858.79
19            2445    8612.85                691.91
20            2448   24478.88               1659.03
21            2459    9156.23                748.24
22            2460   33731.76               2782.46
23            2465   31101.60               2059.03
24            2475   15471.14               1518.18
25            2478   24303.27               1263.00
26            2487   28900.96               2547.85
27            2498    3040.01                294.39
28            2500  182871.72              12201.70
29            2501  174349.30              12024.85
...            ...        ...                   ...
1348          5185    1586.07                112.45
1349          5186     639.66                 38.99
1350          5187    5628.71                303.28
1351          5188    2614.63                159.85
1352          5189     672.60                 49.50
1353          5190    2884.64                217.50
1354          5191     468.66                 37.50
1355          5192     123.60                  8.25
1356          5193     139.50                  9.00
1357          5195      92.50                  5.10
1358          5196     975.13                 49.97
1359          5198   10864.17                592.87
1360          5199    5296.62                339.04
1361          5201     289.78                  8.63
1362          5202     407.61                 23.62
1363          5203    3916.52                267.05
1364          5204    2498.23                176.12
1365          5205     362.16                 31.75
1366          5206    2712.63                250.80
1367          5207    8311.30                335.29
1368          5211    1210.13                101.45
1369          5212    1231.72                 78.15
1370          5213     642.38                 55.60
1371          5215    2255.64                129.39
1372          9001   28916.76                657.00
1373          9002   39083.16               1291.50
1374          9010    5935.44                221.40
1375          9013    2579.04                201.00
1376          9018    6435.00                225.00
1377          9023     633.36                 18.00

[1378 rows x 3 columns]

In [23]:
store_summary.columns = ['Store Number', 'Store Sales', 'Store Volume']
print store_summary.sort(['Store Sales'], ascending=False)
# we can look at the top 10 performing stores by sales, matches up almost perfectly with by volume.
# but now lets look at the hint he gave us, that some stores weren't open all of 2015.
# I have already converted the time to dates so that will help.

      Store Number  Store Sales  Store Volume
125           2633   1215399.02      75757.25
1032          4829   1081941.88      63247.24
36            2512    531684.42      33373.94
194           3385    504057.23      36082.00
200           3420    398025.24      28552.50
389           3952    390443.65      21665.01
323           3814    310536.40      16252.50
306           3773    297914.31      16169.57
193           3354    295039.20      21266.25
153           2670    281356.57      17328.38
204           3447    262524.16      18233.50
1269          5102    236355.41      16092.81
119           2625    220741.89      14741.58
123           2629    218893.55      14043.65
499           4167    215110.71      13100.97
92            2593    212421.23      14997.75
216           3524    202673.94      13941.00
147           2663    200745.16      11803.87
327           3820    197377.85      11087.59
134           2648    192369.52      11044.92
111           2616    189852.50      13178.79
28            2500    182871.72      12201.70
69            2561    182664.67      12524.67
209           3477    182502.42      12360.00
110           2614    179035.77      12823.84
212           3494    178352.22      14341.50
0             2106    176517.45      11836.10
591           4312    176332.10       9728.26
32            2506    176158.09      11291.36
29            2501    174349.30      12024.85
...            ...          ...           ...
950           4737       642.24         48.00
263           3677       641.01         58.25
1349          5186       639.66         38.99
604           4335       634.94         45.75
1377          9023       633.36         18.00
1198          5030       600.55         48.37
888           4672       597.45         46.75
183           2961       592.58         28.00
1133          4954       570.60         72.60
1339          5175       524.80         34.40
1354          5191       468.66         37.50
1325          5161       463.40         24.25
1162          4990       420.81         34.50
1342          5178       420.01         21.60
1362          5202       407.61         23.62
986           4776       376.56         39.00
463           4121       375.06         27.00
1365          5205       362.16         31.75
988           4778       305.88         14.70
1361          5201       289.78          8.63
1034          4834       270.72         24.00
1296          5130       246.40         10.50
1223          5056       174.65          6.78
1356          5193       139.50          9.00
1355          5192       123.60          8.25
433           4059       105.41         11.00
1357          5195        92.50          5.10
1220          5053        67.49          0.75
1120          4939        53.40          4.35
800           4567        44.14          3.00

[1378 rows x 3 columns]

/home/dsi-student/.conda/envs/econ/lib/python2.7/site-packages/ipykernel/__main__.py:2: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  from ipykernel import kernelapp as app

In [37]:
## Would like to seperate the year by quarters using the dates of the sales, we need to group the store number with it's first date of sale and it's last day of sale.
# find the first and last sales date to determine which stores were open all of 2015
dates = booze.groupby(by=['Store Number'], as_index=False)
dates = dates.agg({"Date":[np.min, np.max]})
# aggregating the store number with it's minimum date and maximum date
dates.columns = [''.join(col).strip() for col in dates.columns.values]
# creating columns for the date min and date max

In [40]:
print dates.sort("Dateamin")
# we can see some stores were open very briefly, for instance the first store listed was only open about 2 months

      Store Number   Dateamin   Dateamax
182           2959 2015-01-05 2015-03-25
207           3461 2015-01-05 2016-03-28
208           3465 2015-01-05 2016-03-21
211           3488 2015-01-05 2016-03-28
215           3521 2015-01-05 2016-03-28
217           3525 2015-01-05 2016-03-28
222           3549 2015-01-05 2016-03-28
223           3562 2015-01-05 2016-03-28
224           3563 2015-01-05 2016-03-28
1003          4794 2015-01-05 2016-03-28
536           4230 2015-01-05 2016-03-28
535           4229 2015-01-05 2016-03-28
1146          4972 2015-01-05 2016-03-28
533           4223 2015-01-05 2016-03-21
233           3606 2015-01-05 2016-03-28
1165          4993 2015-01-05 2016-03-28
234           3611 2015-01-05 2016-03-28
236           3618 2015-01-05 2016-03-28
532           4222 2015-01-05 2016-01-15
1009          4800 2015-01-05 2016-03-21
242           3628 2015-01-05 2016-03-28
244           3631 2015-01-05 2015-08-24
247           3644 2015-01-05 2016-03-28
514           4189 2015-01-05 2016-03-28
1144          4970 2015-01-05 2016-03-28
1143          4969 2015-01-05 2016-03-31
513           4188 2015-01-05 2015-05-11
252           3651 2015-01-05 2016-03-28
1015          4806 2015-01-05 2016-03-28
510           4184 2015-01-05 2016-03-28
...            ...        ...        ...
1347          5183 2015-10-20 2016-02-09
1317          5152 2015-10-20 2016-03-01
1353          5190 2015-10-21 2016-03-30
1376          9018 2015-10-27 2015-10-27
174           2853 2015-10-28 2016-02-24
1358          5196 2015-11-05 2016-03-24
1359          5198 2015-11-09 2016-03-28
1351          5188 2015-11-11 2016-03-09
175           2854 2015-11-12 2016-03-22
1360          5199 2015-11-18 2016-03-30
1354          5191 2015-11-30 2016-03-14
1364          5204 2015-11-30 2016-03-28
1361          5201 2015-12-01 2015-12-01
545           4247 2015-12-01 2015-12-29
1349          5186 2015-12-02 2016-03-30
1363          5203 2015-12-03 2016-03-31
1365          5205 2015-12-03 2016-03-24
1367          5207 2015-12-09 2016-03-30
1366          5206 2015-12-14 2016-03-28
1355          5192 2015-12-15 2016-03-15
1369          5212 2015-12-18 2016-03-31
1356          5193 2015-12-22 2015-12-22
1370          5213 2015-12-26 2016-03-28
1371          5215 2015-12-30 2016-03-31
1287          5120 2016-01-06 2016-02-03
1296          5130 2016-01-20 2016-02-22
1357          5195 2016-02-08 2016-02-08
1368          5211 2016-02-09 2016-03-30
1377          9023 2016-03-08 2016-03-08
1362          5202 2016-03-22 2016-03-22

[1378 rows x 3 columns]

/home/dsi-student/.conda/envs/econ/lib/python2.7/site-packages/ipykernel/__main__.py:1: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  if __name__ == '__main__':

In [57]:
# We want stores that have made a sale before Q2 and after Q4 of 2015, essentially open for all of 2015
Q2_2015 = pd.Timestamp("20150301")
Q4_2015 = pd.Timestamp("20151001")
open_2015 = (dates['Dateamin'] < Q2_2015) & (dates['Dateamax'] > Q4_2015)
# created a dataframe of stores that had a sale before Q2 and after Q4
open_stores = dates[open_2015]["Store Number"]
# matching with store number
booze = booze[booze['Store Number'].isin(open_stores)]
booze.sort_values(by="Date")
# This isnt the best way to check but I think I was able to drop the correct stores successfully, The store 2959 (from above) seems to have been dropped

,Date,Store Number,City,Zip Code,County Number,County,Category,Category Name,Vendor Number,Item Number,Item Description,Bottle Volume (ml),State Bottle Cost,State Bottle Retail,Bottles Sold,Sales,Volume Sold (Liters),Volume Sold (Gallons)
227439,2015-01-05,2605,CEDAR RAPIDS,52402,57,Linn,1032200,IMPORTED VODKA - MISC,65,34629,Pinnacle Raspberry,750,7.88,11.82,12,141.84,9.00,2.38
68277,2015-01-05,2535,WEST DES MOINES,50265,77,Polk,1031080,VODKA 80 PROOF,434,36308,Hawkeye Vodka,1750,7.17,10.76,24,258.24,42.00,11.10
263904,2015-01-05,2506,BURLINGTON,52601,29,Des Moines,1081600,WHISKEY LIQUEUR,260,66208,Piehole Cherry Pie,750,7.49,11.24,12,134.88,9.00,2.38
193578,2015-01-05,3782,GUTTENBURG,52052,22,Clayton,1031080,VODKA 80 PROOF,260,37998,Smirnoff Vodka 80 Prf,1750,14.75,22.13,2,44.26,3.50,0.92
193605,2015-01-05,2588,CEDAR RAPIDS,52403,57,Linn,1011200,STRAIGHT BOURBON WHISKIES,421,21480,Benchmark Old No. 8,750,6.38,9.57,12,114.84,9.00,2.38
193640,2015-01-05,4943,ELDON,52554,90,Wapello,1062310,SPICED RUM,259,43984,Admiral Nelson Cherry Spiced Rum,750,5.78,8.67,12,104.04,9.00,2.38
263962,2015-01-05,3628,CEDAR RAPIDS,52402,57,Linn,1011300,TENNESSEE WHISKIES,85,26828,Jack Daniels Old #7 Black Lbl,1750,28.69,43.04,12,516.48,21.00,5.55
40451,2015-01-05,4972,MONONA,52159,22,Clayton,1081305,APPLE SCHNAPPS,65,82606,Dekuyper Sour Apple Pucker,750,6.30,9.45,2,18.90,1.50,0.40
54977,2015-01-05,3525,WASHINGTON,52353,92,Washington,1031080,VODKA 80 PROOF,297,35918,Five O'clock Vodka,1750,7.20,10.80,6,64.80,10.50,2.77
50201,2015-01-05,2554,DAVENPORT,52802,82,Scott,1031080,VODKA 80 PROOF,297,35916,Five O'clock Vodka,750,3.37,5.06,12,60.72,9.00,2.38
264014,2015-01-05,3403,COLUMBUS JUNCTION,52738,58,Louisa,1052010,IMPORTED GRAPE BRANDIES,420,48164,Hennessy VSOP Privilege,750,31.00,46.50,2,93.00,1.50,0.40
193764,2015-01-05,2613,COUNCIL BLUFFS,51501,78,Pottawattamie,1082900,MISC. IMPORTED CORDIALS & LIQUEURS,192,65254,Jagermeister Liqueur,375,6.52,9.78,24,234.72,9.00,2.38
61338,2015-01-05,2591,ATLANTIC,50022,15,Cass,1031080,VODKA 80 PROOF,260,38008,Smirnoff Vodka 80 Prf Pet,1750,14.75,22.13,6,132.78,10.50,2.77
40508,2015-01-05,3521,COUNCIL BLUFFS,51501,78,Pottawattamie,1031200,VODKA FLAVORED,260,77847,Smirnoff Vanilla,750,8.25,12.38,12,148.56,9.00,2.38
77596,2015-01-05,2648,WEST DES MOINES,50265,77,Polk,1071100,AMERICAN COCKTAILS,395,58838,Jose Cuervo Authentic Lime Margarita,1750,8.20,12.30,12,147.60,21.00,5.55
48033,2015-01-05,3400,DES MOINES,50317,77,Polk,1022100,TEQUILA,380,89150,Cabrito Reposado,750,10.99,16.49,12,197.88,9.00,2.38
119594,2015-01-05,4487,CEDAR RAPIDS,52402,57,Linn,1011200,STRAIGHT BOURBON WHISKIES,65,19064,Jim Beam,375,4.76,7.14,6,42.84,2.25,0.59
143838,2015-01-05,2573,MUSCATINE,52761,70,Muscatine,1081600,WHISKEY LIQUEUR,421,64858,Fireball Cinnamon Whiskey Mini Dispenser,3000,29.72,44.58,3,133.74,9.00,2.38
143799,2015-01-05,3805,DAVENPORT,52084,82,Scott,1032080,IMPORTED VODKA,35,34421,Grey Goose Vodka Mini,600,20.00,30.00,2,60.00,1.20,0.32
9250,2015-01-05,3679,MONONA,52159,22,Clayton,1081200,CREAM LIQUEURS,305,73053,Rumchata,1000,16.34,24.51,2,49.02,2.00,0.53
97425,2015-01-05,2527,DES MOINES,50315,77,Polk,1011100,BLENDED WHISKIES,154,27629,Prairie Fire,750,9.17,13.76,3,41.28,2.25,0.59
264133,2015-01-05,2521,WEST DES MOINES,50265,77,Polk,1012300,IRISH WHISKIES,370,15626,Jameson,750,14.49,21.74,12,260.88,9.00,2.38
61302,2015-01-05,2512,IOWA CITY,52240,52,Johnson,1062200,PUERTO RICO & VIRGIN ISLANDS RUM,35,43035,Bacardi Gold Rum Pet,750,8.00,12.00,12,144.00,9.00,2.38
242154,2015-01-05,3549,FORT MADISON,52627,56,Lee,1031200,VODKA FLAVORED,380,41783,Uv Blue Raspberry Vodka Mini,500,4.89,7.34,6,44.04,3.00,0.79
242143,2015-01-05,2507,BURLINGTON,52601,29,Des Moines,1081030,COFFEE LIQUEURS,65,67556,Kamora Coffee Liqueur,750,6.30,9.45,6,56.70,4.50,1.19
77730,2015-01-05,2538,WATERLOO,50702,7,Black Hawk,1012100,CANADIAN WHISKIES,115,11586,Black Velvet Reserve,750,7.00,10.50,4,42.00,3.00,0.79
193344,2015-01-05,4540,BELLEVUE,52031,49,Jackson,1031080,VODKA 80 PROOF,260,37996,Smirnoff Vodka 80 Prf,750,8.25,12.38,6,74.28,4.50,1.19
242669,2015-01-05,4184,MUSCATINE,52761,70,Muscatine,1051010,AMERICAN GRAPE BRANDIES,259,52316,Christian Bros Brandy,750,5.92,8.88,3,26.64,2.25,0.59
77465,2015-01-05,3838,BETTENDORF,52722,48,Iowa,1082900,MISC. IMPORTED CORDIALS & LIQUEURS,410,64736,Citronge,750,13.75,20.63,12,247.56,9.00,2.38
98068,2015-01-05,4869,GUTTENBERG,52052,22,Clayton,1012100,CANADIAN WHISKIES,260,11297,Crown Royal Canadian Whisky,1000,18.50,27.75,1,27.75,1.00,0.26
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
166040,2016-03-31,2627,DES MOINES,50310,77,Polk,1081600,WHISKEY LIQUEUR,259,27453,Cinerator Mini,500,4.25,6.38,3,19.14,1.50,0.40
159966,2016-03-31,3769,CEDAR FALLS,50613,7,Black Hawk,1062300,FLAVORED RUM,260,43290,Captain Morgan Coconut Mini,500,4.80,7.20,12,86.40,6.00,1.59
13209,2016-03-31,3582,LEON,50144,27,Decatur,1081390,IMPORTED SCHNAPPS,421,69611,Dr. Mcgillicuddy's Apple Pie Schnapps,750,8.32,12.48,6,74.88,4.50,1.19
117665,2016-03-31,4706,CLINTON,52732,23,Clinton,1012100,CANADIAN WHISKIES,115,11788,Black Velvet,1750,10.45,15.68,12,188.16,21.00,5.55
7387,2016-03-31,2595,DENISON,51442,24,Crawford,1062310,SPICED RUM,65,44308,Calico Jack,1750,9.71,14.57,6,87.42,10.50,2.77
21869,2016-03-31,4988,CEDAR FALLS,50613,7,Black Hawk,1081370,WATERMELON SCHNAPPS,65,82866,Dekuyper Watermelon Pucker,750,6.30,9.45,1,9.45,0.75,0.20
132947,2016-03-31,3993,WATERLOO,50701,7,Black Hawk,1031200,VODKA FLAVORED,205,40191,New Amsterdam Pineapple,200,2.24,3.36,24,80.64,4.80,1.27
187166,2016-03-31,4001,CARROLL,51401,14,Carroll,1012100,CANADIAN WHISKIES,115,11776,Black Velvet,750,5.23,7.85,12,94.20,9.00,2.38
257470,2016-03-31,5102,MOUNT VERNON,52314,57,Linn,1081900,MISC. AMERICAN CORDIALS & LIQUEURS,65,85526,Dekuyper Signature Blue Curacao,750,5.25,7.88,12,94.56,9.00,2.38
246769,2016-03-31,4077,WATERLOO,50703,7,Black Hawk,1031080,VODKA 80 PROOF,297,35926,Five O'clock PET Vodka,750,3.37,5.06,12,60.72,9.00,2.38
229543,2016-03-31,4502,WATERLOO,50703,7,Black Hawk,1031080,VODKA 80 PROOF,205,36967,New Amsterdam,200,2.24,3.36,24,80.64,4.80,1.27
18239,2016-03-31,2616,CLINTON,52732,23,Clinton,1032200,IMPORTED VODKA - MISC,115,33663,Svedka Strawberry Lemonade,750,8.25,12.38,2,24.76,1.50,0.40
29771,2016-03-31,3713,MASON CITY,50401,17,Cerro Gordo,1012100,CANADIAN WHISKIES,55,12408,Canadian Ltd Whisky,1750,9.14,13.71,6,82.26,10.50,2.77
224143,2016-03-31,2633,DES MOINES,50320,77,Polk,1022100,TEQUILA,65,88556,Sauza Blanco Silver,750,9.45,14.18,12,170.16,9.00,2.38
247932,2016-03-31,2130,WATERLOO,50703,7,Black Hawk,1031080,VODKA 80 PROOF,260,37418,Popov Vodka 80 Prf,1750,8.50,12.75,12,153.00,21.00,5.55
157451,2016-03-31,4958,CEDAR FALLS,50613,7,Black Hawk,1012100,CANADIAN WHISKIES,971,14192,Pendleton Canadian Whisky,750,13.10,19.65,1,19.65,0.75,0.20
79708,2016-03-31,4802,DES MOINES,50310,77,Polk,1011300,TENNESSEE WHISKIES,85,26826,Jack Daniels Old #7 Black Lbl,750,15.07,22.61,12,271.32,9.00,2.38
20790,2016-03-31,3769,CEDAR FALLS,50613,7,Black Hawk,1062300,FLAVORED RUM,260,43314,Captain Morgan Grapefruit,750,8.50,12.75,12,153.00,9.00,2.38
159850,2016-03-31,2633,DES MOINES,50320,77,Polk,1041100,AMERICAN DRY GINS,380,31719,Phillips Gin,1000,4.38,6.57,24,157.68,24.00,6.34
236355,2016-03-31,2626,DES MOINES,50311,77,Polk,1011500,STRAIGHT RYE WHISKIES,255,27102,Templeton Rye,750,18.09,27.14,6,162.84,4.50,1.19
71571,2016-03-31,4493,CEDAR RAPIDS,52404,57,Linn,1012100,CANADIAN WHISKIES,260,10818,Crown Royal Maple,750,15.00,22.50,6,135.00,4.50,1.19
225366,2016-03-31,3831,MADRID,50156,8,Boone,1032200,IMPORTED VODKA - MISC,370,34052,Absolut Raspberri,750,11.49,17.24,2,34.48,1.50,0.40
268420,2016-03-31,4601,DES MOINES,50317,77,Polk,1011200,STRAIGHT BOURBON WHISKIES,65,19061,Jim Beam Mini,500,6.83,10.25,2,20.50,1.00,0.26
146028,2016-03-31,4941,URBANDALE,50322,77,Polk,1022100,TEQUILA,395,89196,Jose Cuervo Especial Reposado Tequila,750,10.49,15.74,12,188.88,9.00,2.38
150232,2016-03-31,4190,JEFFERSON,50129,37,Greene,1081400,TRIPLE SEC,434,86506,Paramount Triple Sec,750,3.42,5.13,3,15.39,2.25,0.59
220718,2016-03-31,2627,DES MOINES,50310,77,Polk,1032080,IMPORTED VODKA,962,36406,Medea,750,18.84,28.26,6,169.56,4.50,1.19
87258,2016-03-31,3647,CLINTON,52732,23,Clinton,1031080,VODKA 80 PROOF,260,37998,Smirnoff Vodka 80 Prf,1750,14.75,22.13,6,132.78,10.50,2.77
224132,2016-03-31,4829,DES MOINES,50314,77,Polk,1032200,IMPORTED VODKA - MISC,65,34395,Effen Cucumber,750,14.17,21.26,6,127.56,4.50,1.19
92243,2016-03-31,2612,PERRY,50220,25,Dallas,1031200,VODKA FLAVORED,380,41692,Uv Blue (raspberry) Vodka,1750,10.99,16.49,3,49.47,5.25,1.39
177648,2016-03-31,4158,CARROLL,51401,14,Carroll,1071100,AMERICAN COCKTAILS,395,58868,Jose Cuervo Authentic Strawberry Margarita,1750,8.20,12.30,30,369.00,52.50,13.87

In [58]:
agg_columns1 = ['Sales', 'Volume Sold (Liters)']
print agg_columns1
# re-doing this to see if I dropped correct stores. Aggregating just these two columns of interest in order to use groupby more efficiently

['Sales', 'Volume Sold (Liters)']

In [59]:
store_summary2 = booze.groupby('Store Number')[agg_columns].sum().reset_index()
print store_summary2.head()

   Store Number      Sales  Volume Sold (Liters)
0          2106  176517.45              11836.10
1          2113   11376.12                836.85
2          2130  139440.02               8436.27
3          2152    8625.74                720.87
4          2178   29912.68               2437.92

In [60]:
store_summary2.columns = ['Store Number', 'Store Sales', 'Store Volume']
print store_summary2.sort(['Store Sales'], ascending=False)
# The top stores shouldn't be changed that much because you would assume the stores were open for all of 2015.
# But we can see at the bottom that now our store total is only 1161, so we dropped 217 stores

      Store Number  Store Sales  Store Volume
123           2633   1215399.02      75757.25
952           4829   1081941.88      63247.24
35            2512    531684.42      33373.94
179           3385    504057.23      36082.00
185           3420    398025.24      28552.50
364           3952    390443.65      21665.01
301           3814    310536.40      16252.50
284           3773    297914.31      16169.57
178           3354    295039.20      21266.25
151           2670    281356.57      17328.38
188           3447    262524.16      18233.50
1157          5102    236355.41      16092.81
117           2625    220741.89      14741.58
121           2629    218893.55      14043.65
467           4167    215110.71      13100.97
91            2593    212421.23      14997.75
199           3524    202673.94      13941.00
145           2663    200745.16      11803.87
305           3820    197377.85      11087.59
132           2648    192369.52      11044.92
109           2616    189852.50      13178.79
27            2500    182871.72      12201.70
68            2561    182664.67      12524.67
192           3477    182502.42      12360.00
108           2614    179035.77      12823.84
195           3494    178352.22      14341.50
0             2106    176517.45      11836.10
553           4312    176332.10       9728.26
31            2506    176158.09      11291.36
28            2501    174349.30      12024.85
...            ...          ...           ...
1094          5024      1886.04        152.10
960           4843      1876.87        100.13
1150          5094      1867.14        159.97
868           4724      1841.04        162.00
600           4388      1828.81        126.03
562           4325      1827.87        149.25
956           4838      1775.19        119.40
711           4527      1773.60        195.00
990           4880      1700.85        161.85
1043          4948      1665.08        134.37
713           4529      1651.98        154.50
893           4753      1637.10        121.35
815           4659      1622.25        143.10
1019          4915      1580.99        102.81
852           4707      1566.72         94.50
1101          5035      1559.34         83.55
685           4498      1481.97        133.05
901           4766      1472.66         52.79
837           4689      1201.62         84.00
851           4706      1187.10         96.00
1137          5078      1185.51         66.96
1141          5082      1156.23         88.19
1055          4968      1054.86         96.00
1028          4929      1039.80         82.50
970           4855      1038.36         87.00
973           4858       970.07         61.16
1111          5047       894.24         40.50
1075          4996       821.22         51.00
940           4811       812.44         48.15
244           3677       641.01         58.25

[1161 rows x 3 columns]

/home/dsi-student/.conda/envs/econ/lib/python2.7/site-packages/ipykernel/__main__.py:2: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  from ipykernel import kernelapp as app

In [ ]:
## I decided to drop stores that were not open for all of 2015 because this seemed to be the most practical
# and we only lost a little of our dataset. Another idea i contemplated was calculating the sales per quarter
# for each store and then taking the mean sales of their quarters and using this to replace stores that had
# missing data for a quarter. Example: if a store averaged $25k in sales for Q3 and Q4 2015, but was not opened
# in Q1 and Q2, I was going to put $25k for quarter sales in Q1 and Q2. But upon forther thought, I thought this
# prediction would not be accurate because those sales would have been "taken" from a store nearby. Thus this
# idea started to become too complicated.


## 5. Case 1 - Proposals for new tax rates 

---

You are an economist working for the Iowa State tax board. The Iowa State legislature is considering changes in the liquor tax rates and has assigned you to the project.

### 5.1 Calculate yearly liquor sales for each store in 2015.

In [80]:
# We want sales per store for JUST 2015
booze.sort_values(by=["Store Number", "Date"], inplace=True)
start_date = pd.Timestamp("20150101")
end_date = pd.Timestamp("20151231")
yr_2015 = (booze['Date'] >= start_date) & (booze['Date'] <= end_date)
sales = booze[yr_2015]

# groupby store number
sales = sales.groupby(by=["Store Number"], as_index=False)

# compute sums and means
sales = sales.agg({"Sales": [np.sum, np.mean],
                   "Volume Sold (Gallons)": [np.sum, np.mean]})

sales.head()

  Store Number      Sales             Volume Sold (Gallons)
                      sum        mean                   sum      mean
0         2106  146038.70  277.640114               2568.16  4.882433
1         2113    9310.22   63.334830                174.29  1.185646
2         2130  111583.91  285.380844               1817.48  4.648286
3         2152    7721.08   54.759433                167.28  1.186383
4         2178   24324.18  102.633671                506.50  2.137131

### 5.2 Calculate the profit each store is making in 2015.

In [131]:
booze['Profit'] = (booze["State Bottle Retail"] - booze['State Bottle Cost']) * booze["Bottles Sold"]
booze['Profit per Gallon'] = booze['Profit'] / booze['Volume Sold (Gallons)']
booze.head()

,Date,Store Number,City,Zip Code,County Number,County,Category,Category Name,Vendor Number,Item Number,...,Bottle Volume (ml),State Bottle Cost,State Bottle Retail,Bottles Sold,Sales,Volume Sold (Liters),Volume Sold (Gallons),Profit,Price per Gallon,Profit per Gallon
22111,2015-01-08,2106,CEDAR FALLS,50613,7,Black Hawk,1062200,PUERTO RICO & VIRGIN ISLANDS RUM,35,43127,...,1000,9.50,14.25,36,513.00,36.0,9.51,171.00,53.943218,17.981073
47659,2015-01-08,2106,CEDAR FALLS,50613,7,Black Hawk,1022100,TEQUILA,410,88296,...,750,27.00,40.50,12,486.00,9.0,2.38,162.00,204.201681,68.067227
65214,2015-01-08,2106,CEDAR FALLS,50613,7,Black Hawk,1062310,SPICED RUM,259,43026,...,750,5.78,8.67,12,104.04,9.0,2.38,34.68,43.714286,14.571429
66346,2015-01-08,2106,CEDAR FALLS,50613,7,Black Hawk,1081200,CREAM LIQUEURS,305,73055,...,750,12.50,18.75,12,225.00,9.0,2.38,75.00,94.537815,31.512605
80570,2015-01-08,2106,CEDAR FALLS,50613,7,Black Hawk,1062200,PUERTO RICO & VIRGIN ISLANDS RUM,434,46351,...,1000,4.34,6.51,12,78.12,12.0,3.17,26.04,24.643533,8.214511

In [89]:
booze.groupby(['Store Number'], sort=True)[['Profit']].sum().sort_values(by=['Profit'], ascending=False).reset_index().head(10)
#Here is the 10 stores by profit, with stores #2633 and #4829 appearing to be outliers. Will look into this more later
# They could be stores near college towns or in highly populated areas

   Store Number     Profit
0          2633  405404.53
1          4829  360959.43
2          2512  177473.98
3          3385  168584.48
4          3420  132971.22
5          3952  130292.29
6          3814  104045.40
7          3773   99353.66
8          3354   98476.89
9          2670   93933.61

### 5.3 Investigate which Iowa counties are making the most profit on liquor per gallon in 2015.

In [101]:
agg_profit = ['Profit', 'Profit per Gallon']
print agg_profit

['Profit', 'Profit per Gallon']

In [103]:
booze.groupby(['County'], sort=True)[agg_profit].sum().sort_values(by=['Profit per Gallon'], ascending=False).reset_index().head(10)

          County      Profit  Profit per Gallon
0           Polk  2371640.25       1.101625e+06
1           Linn  1018664.74       5.145231e+05
2          Scott   812584.87       3.919899e+05
3     Black Hawk   629656.94       3.398969e+05
4        Johnson   667241.51       3.057563e+05
5          Story   351301.66       2.045464e+05
6  Pottawattamie   422231.50       1.997817e+05
7       Woodbury   413866.24       1.963431e+05
8        Dubuque   353883.41       1.704611e+05
9    Cerro Gordo   230437.61       1.372670e+05

### 5.4  Does profit scale proportionally to store size?

Size of a store can be defined as the total gallons sold in 2015. Is the profit to store size ratio increasing as store size increases? Decreasing? Consistent?

In [104]:
agg_size = ['Profit', 'Volume Sold (Gallons)']
print agg_size

['Profit', 'Volume Sold (Gallons)']

In [106]:
booze.groupby(['Store Number'], sort=True)[agg_size].sum().sort_values(by=['Profit'], ascending=False).reset_index().head(10)
# We can see from the top 10 that store size (defined by volume of gallons sold) is not perfectly correlated with profit

   Store Number     Profit  Volume Sold (Gallons)
0          2633  405404.53               20014.37
1          4829  360959.43               16709.87
2          2512  177473.98                8817.12
3          3385  168584.48                9532.05
4          3420  132971.22                7542.98
5          3952  130292.29                5724.06
6          3814  104045.40                4293.54
7          3773   99353.66                4270.94
8          3354   98476.89                5618.08
9          2670   93933.61                4577.90

### 5.5 Create a broader category for liquor type.

Liquor types are pretty granular in this dataset. Create a column that categorizes these types into a smaller amount of categories. The categories you decide on are up to you.

In [117]:
alc_type={1: "whiskey", 2: "vodka", 3: "rum", 4: "beer"}

In [114]:
print alc_type

{1: 'whiskey', 2: 'vodka', 3: 'rum', 4: 'beer'}

In [115]:
print alc_type[2]

vodka

In [119]:
booze["alc_type"]=booze['alc_type']=="whiskey" if booze["Category Number"]==1011100.0
## I dont know how to do this, and it has taken me too long. I am going to move on.

SyntaxError: invalid syntax (<ipython-input-119-9e26f8a44793>, line 1)

### 5.6 Do relationships exist between the broader liquor type and profit?

In [110]:
## okay tried quite a few options for 5.5 ie data dictionary and trying to create a column. Unfortunately unsuccesfully
## I can think of a way to do this with dummy variables but im not sure it applies here
## To answer the question tho, one would imagine cheap, hard liquor such as vodka, whiskey and rum, are more profitable. (Not based on personal experience)

TypeError: 'DataFrame' object is not callable


### 5.7 Are there any noticeable relationships between liquor brand and sales? Profit?

In [134]:
booze.groupby(['Item Description'], sort=True)[['Sales']].sum().sort_values(by=['Sales'], ascending=False).reset_index().head(10)
#sales is equal to bottles sold times bottle retail cost

                Item Description       Sales
0                   Black Velvet  1491563.84
1  Jack Daniels Old #7 Black Lbl  1149337.98
2      Captain Morgan Spiced Rum  1136632.52
3      Fireball Cinnamon Whiskey   870722.53
4    Crown Royal Canadian Whisky   766194.22
5                  Hawkeye Vodka   676471.86
6   Absolut Swedish Vodka 80 Prf   659287.77
7               Grey Goose Vodka   594094.97
8                        Jameson   481765.51
9           Jagermeister Liqueur   478457.99

In [130]:
booze.groupby(['Item Description'], sort=True)[['Volume Sold (Gallons)']].sum().sort_values(by=['Volume Sold (Gallons)'], ascending=False).reset_index().head(10)
## black velvet makes quite a few liquors but I believe it's main one is whiskey
# the top 10 is made up of whiskey, vodka and rum.

                Item Description  Volume Sold (Gallons)
0                   Black Velvet               42969.95
1                  Hawkeye Vodka               28151.56
2      Captain Morgan Spiced Rum               17597.93
3                   Barton Vodka               14686.50
4             Five O'clock Vodka               14633.15
5      Fireball Cinnamon Whiskey               14228.12
6  Jack Daniels Old #7 Black Lbl               11027.22
7                 Phillips Vodka                9484.48
8   Absolut Swedish Vodka 80 Prf                8160.73
9           Bacardi Superior Rum                8013.99

In [132]:
agg_brand = ['Volume Sold (Gallons)', 'Profit per Gallon']
print agg_brand

['Volume Sold (Gallons)', 'Profit per Gallon']

In [137]:
booze.groupby(['Item Description'], sort=True)[agg_brand].sum().sort_values(by=['Profit per Gallon'], ascending=False).reset_index().head(10)
## We can see that the top ten changes when profit per gallon is included. We see that some "premium" liquors such as Grey Goose and Jack Daniels Black Label, are extremely profitable but don't necessarily sell the most gallons.

                Item Description  Volume Sold (Gallons)  Profit per Gallon
0  Jack Daniels Old #7 Black Lbl               11027.22      105017.866736
1               Grey Goose Vodka                4567.03       96623.200761
2                   Black Velvet               42969.95       87296.566799
3    Crown Royal Canadian Whisky                7229.15       79990.525858
4   Absolut Swedish Vodka 80 Prf                8160.73       78440.963937
5           Jagermeister Liqueur                5331.22       70683.875068
6      Captain Morgan Spiced Rum               17597.93       70636.227495
7                    Hennessy VS                1327.12       67592.587605
8          Smirnoff Vodka 80 Prf                7278.76       67243.606334
9                       Jim Beam                6074.82       65517.445099

### 5.8 The tax board wants to design a tax or taxes that affect larger stores more than smaller "mom and pop" stores.

Based on your investigations into the data, come up with a way you could design a tax that achieves this goal **without explicitly taxing stores based on size or county critera.** The liqour board does not want to obviously punish larger stores or speific counties for fear of backlash, but is willing to tax hard alcohol more than beer, for example.

Feel free to do more EDA if it helps.

Your report should describe whether such a tax is possible or not, and the specifics of what the tax will target/do.

In [ ]:
# larger stores are able to carry more "premium" liquors and buy them in bulk and reap the benefits of their
# high retail cost. Mom and pop stores are unable to do this. We can see that these premium alcohols often have
# a +$7 profit margin per bottle (ie jack daniels black label, grey goose). Thus I suggest that law makers add
# a tax to the state bottle cost of premium alcohols, while simultaneously not allowing stores to raise the retail price of said bottles.
# This will not increase the input cost felt by vendors but rather it will be felt by the stores. This will also
# not increase the cost for consumers. This will ideally, reduce the profit margins for these high end liquors
# and only slightly alter demand from stores to vendors while not reducing demand from consumers. 

# I do not knowing extensively Iowa liquor laws but it appears that each bottle already has a set state bottle retail price
# thus if we do not allow these to raises, but add a tax only to the cost stores have to pay, so they pay the
# same amount to the vendors but then an added tax goes to the state. This appears to be plausible and would
# affect larger stores more than "mom and pop" ones.


## 6. Case 2 = Market research for new store locations 

A liquor store owner in Iowa is looking to open a store in a new location and has hired you as a consultant to investigate the market data for potential new locations. The business owner is interested in what you can discover from the data that will help him evaluate a good location for a new storefront.

---

### 6.1 Create columns for Q1 2015 sales and Q1 2016 sales.

The owner is not just interested in what locations are currently selling well, but also which areas are showing the most promising sales growth from 2015 to 2016. 

For yearly changes we will focus on the changes from Q1 2015 to Q1 2016 specifically (avoiding effects of season changes).

Note: Q1 is months: January, February, and March.

In [149]:
start_dateQ1 = pd.Timestamp("20150101")
end_dateQ1 = pd.Timestamp("20150331")
Q1_2015 = (booze['Date'] >= start_dateQ1) & (booze['Date'] <= end_dateQ1)
## created Q1 of 2015

start_yr2016_Q1 = pd.Timestamp("20160101")
end_yr2016_Q1 = pd.Timestamp("20160331")
Q1_2016 = (booze['Date'] >= start_yr2016_Q1) & (booze['Date'] <= end_yr2016_Q1)

Q1_2015.groupby(['Store Number'], sort=True)[['Sales']].sum().sort_values(by=['Sales'], ascending=False).reset_index().head(10)

KeyError: 'Store Number'

### 6.2 Decide on a metric for performance that combines Q1 2016 sales as well as growth in sales from Q1 2015.

Again, the owner wants to know that his store will be in a good position to sell a large amount of liquor now, but also have his store be more likely to grow and sell even more going forward. 

In particular, he is worried about opening a store in an area that is showing a decline in liquor sales between Q1 2015 and Q1 2016.

In [ ]:
#Show the percent change in sales from Q1 2015 to Q1 2016. Find out the number of stores in that county to see
# if the county is saturated. Possibly look at the population of each county. See which county has a low number
# of stores, with a good size population, and has a growth in sales from 2015 to 2016.

### 6.3 Recommend a location based on your metric.

The owner asks you to make a recommendation for a new store location. Explain why you recommended this area.

In [ ]:
# I could not figure out the code for growth in sales, I do not know why but once I made seperate dataframes
# for Q1 of 2015 and 2016 I couldn't groupby sales. I worked by myself and honestly I think the answer is
# to the problem with my code isn't that difficult but my brain is fried. This has taken me a long time.
# It appeared though that Polk County was the most profitable, so I would recommend there.

### 6.4 Recommend a location based also on a restricted inventory type.

Your employer has now decided he wants his store to focus on one type of liquor only. He askes you:

1. What would be the best type of liquor to sell to maximize profit?
2. Should the recommended location change if he is only selling one type of liquor?